# Generated by Django 3.1.3 on 2021-06-04 10:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20210530_1148'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='MedicalPersonnel',
        ),
    ]
