# Generated by Django 3.1.3 on 2021-06-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_auto_20210604_1037"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalpersonnel",
            name="level",
            field=models.CharField(
                choices=[("LEAD_SURGEON", "Lead Surgeon")],
                default="Lead Surgeon",
                max_length=255,
            ),
        ),
    ]
