# Generated by Django 3.1.3 on 2021-06-11 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0006_auto_20210604_1406"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalpersonnel",
            name="user",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medical_personnel",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
