# Generated by Django 3.1.3 on 2021-06-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_auto_20210611_1126"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalpersonnel",
            name="level",
            field=models.CharField(
                choices=[
                    ("SURGEON", "Surgeon"),
                    ("LEAD_SURGEON", "Lead Surgeon"),
                    ("NATIONAL_LEAD", "National Lead"),
                ],
                default="LEAD_SURGEON",
                max_length=255,
            ),
        ),
    ]
