# Generated by Django 3.1.3 on 2025-12-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210630_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalpersonnel',
            name='level',
            field=models.CharField(choices=[('SURGEON', 'Surgeon'), ('LEAD_SURGEON', 'Centre Lead'), ('REGIONAL_LEAD', 'Regional Lead'), ('ZONAL_LEAD', 'Zonal Lead'), ('NATIONAL_LEAD', 'National Lead')], default='SURGEON', max_length=255),
        ),
    ]
