# Generated by Django 3.1.3 on 2021-06-04 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "national_id",
                    models.IntegerField(blank=True, null=True, unique=True),
                ),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "day_of_birth",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "month_of_birth",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "year_of_birth",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "gender",
                    models.IntegerField(
                        choices=[
                            ("GENDER_MALE", "Male"),
                            ("GENDER_FEMALE", "Female"),
                        ]
                    ),
                ),
                ("phone_1", models.IntegerField(blank=True, null=True)),
                ("phone_2", models.IntegerField(blank=True, null=True)),
                (
                    "address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientHospitalMapping",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="registry.hospital",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="registry.patient",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Patient-Hospital mapping",
                "unique_together": {("patient", "hospital")},
            },
        ),
    ]
