# Generated by Django 3.1.3 on 2021-06-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0002_auto_20210607_1537"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="national_id",
            field=models.CharField(
                blank=True, max_length=20, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone_1",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone_2",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
