# Generated by Django 3.1.3 on 2021-06-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0004_remove_patient_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")], max_length=32
            ),
        ),
    ]
