# Generated by Django 3.1.3 on 2021-06-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0005_auto_20210607_2222"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="last_name",
        ),
        migrations.AddField(
            model_name="patient",
            name="full_name",
            field=models.CharField(default="default", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female")],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="year_of_birth",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
