# Generated by Django 3.1.3 on 2021-09-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0007_episode_followup"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patienthospitalmapping",
            options={"verbose_name_plural": "Patient-Hospital mappings"},
        ),
        migrations.AddField(
            model_name="patienthospitalmapping",
            name="patient_hospital_id",
            field=models.CharField(default="111111", max_length=256),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="patienthospitalmapping",
            unique_together={
                ("hospital", "patient_hospital_id"),
                ("patient", "hospital"),
            },
        ),
    ]
