# Generated by Django 3.1.3 on 2021-09-19 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0008_auto_20210919_1826"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patienthospitalmapping",
            name="hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_mappings",
                to="registry.hospital",
            ),
        ),
        migrations.AlterField(
            model_name="patienthospitalmapping",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hospital_mappings",
                to="registry.patient",
            ),
        ),
    ]
