# Generated by Django 3.1.3 on 2021-10-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0009_auto_20210919_1941"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("MALE", "Male"), ("FEMALE", "Female")],
                max_length=32,
                null=True,
            ),
        ),
    ]
