# Generated by Django 3.1.3 on 2021-11-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0011_auto_20211119_1518"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female")],
                max_length=32,
                null=True,
            ),
        ),
    ]
