# Generated by Django 3.1.3 on 2022-02-22 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0013_discharge"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="episode",
            name="discharge_date",
        ),
    ]
