# Generated by Django 3.1.3 on 2022-02-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0015_auto_20220222_1043"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("MALE", "Male"), ("FEMALE", "Female")],
                max_length=32,
                null=True,
            ),
        ),
    ]
