# Generated by Django 3.1.3 on 2022-10-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0017_auto_20221029_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='side',
            field=models.CharField(choices=[('NA', 'Not Applicable'), ('LEFT', 'Left'), ('RIGHT', 'Right')], max_length=16),
        ),
        migrations.AlterField(
            model_name='episode',
            name='type',
            field=models.CharField(choices=[('NA', 'Not Applicable'), ('DIRECT', 'Direct'), ('INDIRECT', 'Indirect'), ('PANTALOON', 'Pantaloon')], max_length=16),
        ),
    ]
