# Generated by Django 3.1.3 on 2023-04-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0024_auto_20230404_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discharge',
            name='infection',
            field=models.CharField(max_length=64),
        ),
    ]
