# Generated by Django 3.1.3 on 2023-04-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0025_auto_20230404_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='discharge',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
