# Generated by Django 3.1.3 on 2023-04-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0027_auto_20230404_1555"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="antibiotic_type",
            field=models.CharField(
                default="+24hrs Post Op Oral", max_length=128
            ),
            preserve_default=False,
        ),
    ]
