# Generated by Django 3.1.3 on 2023-04-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0028_auto_20230404_1842"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="antibiotic_type",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
