# Generated by Django 3.1.3 on 2023-05-25 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0022_auto_20230525_0641'),
        ('registry', '0032_remove_episode_comments'),
    ]

    operations = [
    ]
