# Generated by Django 3.1.3 on 2024-07-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0035_episode_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="followup",
            name="recurrence",
            field=models.BooleanField(null=True),
        ),
    ]
