# Generated by Django 3.1.3 on 2024-09-15 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0037_preferredhospital'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patienthospitalmapping',
            options={'verbose_name_plural': 'Patient-Hospital Mappings'},
        ),
    ]
