# Generated by Django 3.1.3 on 2025-05-19 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0037_preferredhospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Zones',
            },
        ),
        migrations.AlterModelOptions(
            name='patienthospitalmapping',
            options={'verbose_name_plural': 'Patient-Hospital Mappings'},
        ),
        migrations.CreateModel(
            name='RegionZoneMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zone_mapping', to='registry.region')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_mappings', to='registry.zone')),
            ],
            options={
                'verbose_name_plural': 'Region-Zone Mappings',
            },
        ),
        migrations.CreateModel(
            name='HospitalRegionMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='region_mapping', to='registry.hospital')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_mappings', to='registry.region')),
            ],
            options={
                'verbose_name_plural': 'Hospital-Region Mappings',
            },
        ),
    ]
