# Generated by Django 3.1.3 on 2024-09-18 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_auto_20210630_1407"),
        ("registry", "0038_auto_20240915_1210"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="primary_surgeon",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="primary_surgeon",
                to="users.medicalpersonnel",
            ),
        ),
        migrations.AddField(
            model_name="episode",
            name="secondary_surgeon",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="secondary_surgeon",
                to="users.medicalpersonnel",
            ),
        ),
        migrations.AddField(
            model_name="episode",
            name="tertiary_surgeon",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="tertiary_surgeon",
                to="users.medicalpersonnel",
            ),
        ),
    ]
