# Generated by Django 3.1.3 on 2025-05-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0038_auto_20250519_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_text', models.TextField()),
                ('display_from', models.DateTimeField(blank=True, null=True)),
                ('display_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
