# Generated by Django
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_auto_20210630_1407"),
        ("registry", "0040_episode_primary_surgeons"),
    ]

    operations = [
        migrations.AddField(
            model_name="followup",
            name="primary_attendee",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="followup_primary_attendee",
                to="users.medicalpersonnel",
            ),
        ),
        migrations.AddField(
            model_name="followup",
            name="secondary_attendee",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="followup_secondary_attendee",
                to="users.medicalpersonnel",
            ),
        ),
        migrations.AddField(
            model_name="followup",
            name="tertiary_attendee",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="followup_tertiary_attendee",
                to="users.medicalpersonnel",
            ),
        ),
    ]
