# Generated by Django 3.2.25 on 2026-06-02 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0041_followup_primary_attendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup',
            name='secondary_attendee',
        ),
        migrations.RemoveField(
            model_name='followup',
            name='tertiary_attendee',
        ),
    ]
