# Generated by Django 3.0.9 on 2020-10-02 06:50
import os
import sys
from pathlib import Path

from django.core.wsgi import get_wsgi_application

if __name__ == "__main__":
    # To run this script you should copy it from folder /scripts/
    # to the top level directory. The command is
    # cp scripts/test.py test.py;python test.py
    # The following code is required in order for django to run temporarily
    # in GitHub Actions.
    # A django environment must be set up before importing
    # tmh_registry packages.
    ROOT_DIR = Path(__file__).resolve(strict=True).parent
    sys.path.append(str(ROOT_DIR / "tmh_registry"))
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings.local")
    application = get_wsgi_application()

from logging import getLogger

logger = getLogger(__name__)


def hello_world():
    """
    Create organizations
    """
    logger.info("Hello world from Django app")


if __name__ == "__main__":
    hello_world()
